_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
architecture:
    value: swin_unet
dataset:
    value: basic
epochs:
    value: 100
learning_rate:
    value: 0.0002
